apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pablitto-broker
  name: pablitto-broker
  namespace: pablitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pablitto-broker
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pablitto-broker
    spec:
      containers:
      - image: romeocontainers/pablitto-broker
        name: pablitto-broker
