apiVersion: v1
kind: Service
metadata:
  labels:
    app: pablitto-broker
  name: pablitto-broker
spec:
  ports:
  - port: 1883
    protocol: TCP
    targetPort: 1883
  selector:
    app: pablitto-broker
  type: NodePort
